/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hfXpSuzxFky
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Cabin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

cabin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"

export function MainPage() {
  return (
    <div className="flex flex-col h-screen">
      <header className="flex items-center justify-between w-full px-4 border-b-2 border-gray-100 sm:px-6">
        <h1 className="text-2xl font-bold leading-6">Sports Partners</h1>
        <div className="relative">
          <div className="flex items-center space-x-2 text-sm rounded-full hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-gray-950 dark:focus:ring-gray-200">
            <img
              alt="Avatar"
              className="rounded-full"
              height="32"
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32"
            />
            <span className="font-semibold">John</span>
          </div>
        </div>
      </header>
      <main className="flex flex-1 flex-col w-full p-4 gap-4 md:gap-6">
        <div className="flex items-center gap-4">
          <Input className="flex-1 min-w-0" placeholder="Search..." type="search" />
          <Button className="h-10" variant="outline">
            Search
          </Button>
        </div>
        <div className="grid w-full min-w-[600px] overflow-auto border border-gray-200 rounded-lg divide-y md:grid-cols-2 dark:border-gray-800">
          <div className="flex items-center p-4 sm:p-6 gap-4">
            <img
              alt="Avatar"
              className="rounded-full"
              height="56"
              src="/placeholder.svg"
              style={{
                aspectRatio: "56/56",
                objectFit: "cover",
              }}
              width="56"
            />
            <div className="flex-1 space-y-2">
              <div className="font-semibold">Alice</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">Tennis, Badminton</div>
            </div>
            <Button size="sm">Partner</Button>
          </div>
          <div className="flex items-center p-4 sm:p-6 gap-4">
            <img
              alt="Avatar"
              className="rounded-full"
              height="56"
              src="/placeholder.svg"
              style={{
                aspectRatio: "56/56",
                objectFit: "cover",
              }}
              width="56"
            />
            <div className="flex-1 space-y-2">
              <div className="font-semibold">Bob</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">Football, Basketball</div>
            </div>
            <Button size="sm">Partner</Button>
          </div>
          <div className="flex items-center p-4 sm:p-6 gap-4">
            <img
              alt="Avatar"
              className="rounded-full"
              height="56"
              src="/placeholder.svg"
              style={{
                aspectRatio: "56/56",
                objectFit: "cover",
              }}
              width="56"
            />
            <div className="flex-1 space-y-2">
              <div className="font-semibold">Charlie</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">Chess, Table Tennis</div>
            </div>
            <Button size="sm">Partner</Button>
          </div>
          <div className="flex items-center p-4 sm:p-6 gap-4">
            <img
              alt="Avatar"
              className="rounded-full"
              height="56"
              src="/placeholder.svg"
              style={{
                aspectRatio: "56/56",
                objectFit: "cover",
              }}
              width="56"
            />
            <div className="flex-1 space-y-2">
              <div className="font-semibold">David</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">Swimming, Volleyball</div>
            </div>
            <Button size="sm">Partner</Button>
          </div>
        </div>
        <div className="flex items-center gap-4 mt-4">
          <fieldset>
            <legend className="font-semibold mb-4 text-sm">Sport</legend>
            <div className="grid gap-2">
              <div className="flex gap-2 items-center">
                <Checkbox id="sport-tennis" />
                <Label className="font-normal" htmlFor="sport-tennis">
                  Tennis
                </Label>
              </div>
              <div className="flex gap-2 items-center">
                <Checkbox id="sport-football" />
                <Label className="font-normal" htmlFor="sport-football">
                  Football
                </Label>
              </div>
              <div className="flex gap-2 items-center">
                <Checkbox id="sport-basketball" />
                <Label className="font-normal" htmlFor="sport-basketball">
                  Basketball
                </Label>
              </div>
              <div className="flex gap-2 items-center">
                <Checkbox id="sport-swimming" />
                <Label className="font-normal" htmlFor="sport-swimming">
                  Swimming
                </Label>
              </div>
            </div>
          </fieldset>
          <fieldset>
            <legend className="font-semibold mb-4 text-sm">Location</legend>
            <div className="grid gap-2">
              <div className="flex gap-2 items-center">
                <Checkbox id="location-usa" />
                <Label className="font-normal" htmlFor="location-usa">
                  USA
                </Label>
              </div>
              <div className="flex gap-2 items-center">
                <Checkbox id="location-uk" />
                <Label className="font-normal" htmlFor="location-uk">
                  UK
                </Label>
              </div>
              <div className="flex gap-2 items-center">
                <Checkbox id="location-germany" />
                <Label className="font-normal" htmlFor="location-germany">
                  Germany
                </Label>
              </div>
              <div className="flex gap-2 items-center">
                <Checkbox id="location-australia" />
                <Label className="font-normal" htmlFor="location-australia">
                  Australia
                </Label>
              </div>
            </div>
          </fieldset>
        </div>
      </main>
      <footer className="flex items-center justify-center w-full p-4 border-t-2 border-gray-100 sm:p-6">
        <div className="text-sm text-gray-500 dark:text-gray-400">Made with ❤️ by WIzeliners</div>
      </footer>
    </div>
  )
}
